name: Autograding
on: [push]
jobs:
  autograding:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check platformio.ini for custom partitions
        id: check1
        uses: education/autograding-command-grader@v1
        with:
          test-name: Check platformio.ini
          setup-command: ""
          command: grep -E "^board_build.partitions\s*=\s*partitions.csv" platformio.ini
          timeout: 10
          max-score: 20

      - name: Check partitions.csv existence
        id: check2
        uses: education/autograding-command-grader@v1
        with:
          test-name: Check partitions.csv
          setup-command: ""
          command: ls partitions.csv
          timeout: 10
          max-score: 20

      - name: Check main.cpp for NVS logic
        id: check3
        uses: education/autograding-command-grader@v1
        with:
          test-name: Check NVS logic
          setup-command: ""
          command: grep "Preferences" src/main.cpp && grep "preferences.begin" src/main.cpp
          timeout: 10
          max-score: 20

      - name: Check main.cpp for LittleFS logic
        id: check4
        uses: education/autograding-command-grader@v1
        with:
          test-name: Check LittleFS logic
          setup-command: ""
          command: grep "LittleFS" src/main.cpp && grep "LittleFS.begin" src/main.cpp
          timeout: 10
          max-score: 20

      - name: Check MemoryMap.md report
        id: check5
        uses: education/autograding-command-grader@v1
        with:
          test-name: Check MemoryMap.md
          setup-command: ""
          command: ls docs/MemoryMap.md
          timeout: 10
          max-score: 20

      - name: Autograding Reporter
        uses: education/autograding-grading-reporter@v1
        env:
          CHECK1_RESULTS: "${{steps.check1.outputs.result}}"
          CHECK2_RESULTS: "${{steps.check2.outputs.result}}"
          CHECK3_RESULTS: "${{steps.check3.outputs.result}}"
          CHECK4_RESULTS: "${{steps.check4.outputs.result}}"
          CHECK5_RESULTS: "${{steps.check5.outputs.result}}"
        with:
          runners: check1,check2,check3,check4,check5
